<a href="https://colab.research.google.com/github/Jzsimmonds/-Data-Science-Bootcamp-2022-5-Data-Science-Projects/blob/main/NUMPYI~1_IPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Numerical Computation

NumPy is an open source Python package for numerical computation in Python

## Installing NumPy

conda install numpy

or

pip install numpy

### Why use NumPy?

- faster and more compact than Python lists
- consumes less memory and is convenient to use
- Other data science packages are built on top of it

# Data Types

In [ ]:
import numpy as np

In [ ]:
x = np.float(1.25844)

<ipython-input-2-a337e6fee48c>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.float(1.25844)


In [ ]:
x

1.25844

In [ ]:
type(x)

float

In [ ]:
w = np.int(1.2222)

<ipython-input-5-d72a2b021e2a>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  w = np.int(1.2222)


In [ ]:
w

1

In [ ]:
type(w)

int

## Ways to Create NumPy Arrays

A NumPy array is a multidimensional array-like data structure

### np.arange()

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Covert Python List to a NumPy Array

In [ ]:
scores = [50,60,70,30,25,70]

In [ ]:
scores_array = np.array(scores)

In [ ]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [ ]:
type(scores_array)

numpy.ndarray

In [ ]:
scores_array.ndim # the dimension of the array

1

In [ ]:
scores_array.size # the number of items in the array

6

In [ ]:
scores_array.dtype # the type of data in the array

dtype('int64')

In [ ]:
np.unique(scores_array) # print unique items from the array

array([25, 30, 50, 60, 70])

In [ ]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [ ]:
np.flip(scores_array) # reverse the array

array([70, 25, 30, 70, 60, 50])

In [ ]:
np.sort(scores_array)

array([25, 30, 50, 60, 70, 70])

In [ ]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [ ]:
np.clip(scores_array, 20,59)

array([50, 59, 59, 30, 25, 59])

# Part Two

### Joining Two Arrays

In [ ]:
array_two = np.array([90, 26, 37, 77, 65, 55])

In [ ]:
scores_array

array([50, 60, 70, 30, 25, 70])

In [ ]:
np.concatenate((scores_array, array_two))

array([50, 60, 70, 30, 25, 70, 90, 26, 37, 77, 65, 55])

### np.zeros()

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones()

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.eye(5) # Return a 2-D array with ones on the diagonal
           # and zeros elsewhere.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.linspace()

In [ ]:
np.linspace(10,50,5) # Return evenly spaced numbers over a
                      # specified interval.
                    # start,stop, num=5,

array([10., 20., 30., 40., 50.])

In [ ]:
np.linspace(10,15,5)

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

In [ ]:
np.random.rand(10)# Create an array of the given shape and
                  # populate it with  random samples from
                   # a uniform distribution

array([0.22066668, 0.07754324, 0.74937691, 0.17973052, 0.70097915,
       0.26150287, 0.51906546, 0.85536094, 0.22334021, 0.22727214])

In [ ]:
np.random.rand(3,2)

array([[0.44244819, 0.50685102],
       [0.63615408, 0.97904163],
       [0.03133164, 0.42256121]])

In [ ]:
np.random.randint(15)

12

In [ ]:
np.random.randint(5,20,6)
# Return random integers from `low` (inclusive) to `high` (exclusive).

array([18, 17, 14, 18,  7, 10])

In [ ]:
np.array([np.nan,6,np.nan])

array([nan,  6., nan])

# Part 3

# Checking Documentation

In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [ ]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

Happy coding!